Features/rhpm ur02
salilsaini868/Recruitment-System pull request #32
Opened 2018-02-05 07:29 UTC by bharathkeerthi

Forgot password screen of validation

2018-02-06 11:54 UTC, salilsaini868 requested changes

2018-02-06 11:54 UTC, salilsaini868 commented on web/src/app/Login/forgotpassword.component.ts
> +        private router: Router) {
what is use of location here ?

2018-02-06 11:54 UTC, salilsaini868 commented on web/src/app/Login/login.component.html
> +                                    <a data-toggle="modal" (click)="navigate()">{{ 'USER.FORGOTPASSWORD' | translate }} </a>
give proper names to function

2018-02-06 11:54 UTC, salilsaini868 commented on web/src/app/Login/shared/forgotpassword.serviceApp.ts
> +
why role service used here ?

2018-02-06 11:54 UTC, salilsaini868 commented on web/src/app/Login/shared/login.module.ts
> +  providers: [LoginServiceApp, ForgotpasswordServiceApp],
use login service for Forgotpassword

2018-02-06 11:55 UTC, salilsaini868 commented
resolve conflicts

2018-02-06 13:23 UTC, bharathkeerthi commented on web/src/app/Login/forgotpassword.component.ts
> +        private router: Router) {
done

2018-02-06 13:23 UTC, bharathkeerthi commented on web/src/app/Login/login.component.html
> +                                    <a data-toggle="modal" (click)="navigate()">{{ 'USER.FORGOTPASSWORD' | translate }} </a>
done

2018-02-06 13:23 UTC, bharathkeerthi commented on web/src/app/Login/shared/forgotpassword.serviceApp.ts
> +
done

2018-02-06 13:23 UTC, bharathkeerthi commented on web/src/app/Login/shared/login.module.ts
> +  providers: [LoginServiceApp, ForgotpasswordServiceApp],
done

2018-02-08 08:58 UTC, salilsaini868 requested changes

2018-02-08 08:58 UTC, salilsaini868 commented on web/src/app/Login/shared/login.serviceApp.ts
> +    constructor(private http: HttpClient, private apiLoginService: LoginService, private apiForgotpasswordService: UserService, private apiRoleService: RoleService) { }
remove them private apiForgotpasswordService: UserService, private apiRoleService: RoleService
or mover to corresponding serices

2018-02-08 08:58 UTC, salilsaini868 commented on web/src/app/Login/shared/login.serviceApp.ts
>      getUser(): Observable<any> {
move this method to corresposnding service

2018-02-08 09:36 UTC, salilsaini868 commented
resolve conflicts

2018-02-08 09:38 UTC, salilsaini868 approved these changes

2018-02-08 09:38 UTC, merged